"""Static presets: robotics roles, career fields, job levels, countries, categories, default profiles."""
from __future__ import annotations

ROBOTICS_ROLES = [
    "Robotics Engineer",
    "Graduate Robotics Engineer",
    "Autonomous Systems Engineer",
    "Autonomy Engineer",
    "Robotics Software Engineer",
    "Field Robotics Engineer",
    "Mobile Robotics Engineer",
    "Perception Engineer",
    "Navigation Engineer",
    "Sensor Fusion Engineer",
    "Robotics Integration Engineer",
    "Test and Validation Engineer",
]

CAREER_FIELDS = [
    "Automation and Control",
    "Robotics and Autonomous Systems",
    "Perception and Computer Vision",
    "Sensor Fusion and Lidar",
    "Systems Engineering and Integration",
    "Electrical and Mechatronics",
    "Embedded Systems and Edge AI",
    "Software Engineering and AI",
    "Mining Automation and Technology",
    "Aerospace and Defence",
    "Graduate and Entry Level",
]

JOB_LEVELS = [
    "Graduate Program",
    "Graduate Engineer",
    "Entry Level",
    "Junior",
    "Associate",
    "Early Career",
]

COUNTRIES = [
    "australia",
    "usa",
    "uk",
    "canada",
    "germany",
    "sweden",
    "switzerland",
    "netherlands",
    "norway",
    "denmark",
    "finland",
    "singapore",
    "new zealand",
    "ireland",
]

SOURCES = ["indeed", "linkedin", "glassdoor", "google"]

# Ordered rules: first match wins. (keyword, category)
CATEGORY_RULES: list[tuple[str, str]] = [
    ("graduate program", "Graduate Program"),
    ("graduate engineer", "Graduate Program"),
    ("grad program", "Graduate Program"),
    ("graduate", "Graduate Program"),
    ("perception", "Perception & CV"),
    ("computer vision", "Perception & CV"),
    ("lidar", "Sensor Fusion"),
    ("sensor fusion", "Sensor Fusion"),
    ("slam", "Sensor Fusion"),
    ("navigation", "Navigation"),
    ("path planning", "Navigation"),
    ("localisation", "Navigation"),
    ("localization", "Navigation"),
    ("autonomy", "Autonomous Systems"),
    ("autonomous", "Autonomous Systems"),
    ("self-driving", "Autonomous Systems"),
    ("field robot", "Field Robotics"),
    ("mobile robot", "Mobile Robotics"),
    ("robotic", "Robotics"),
    ("robot", "Robotics"),
    ("embedded", "Embedded & Edge AI"),
    ("firmware", "Embedded & Edge AI"),
    ("edge ai", "Embedded & Edge AI"),
    ("fpga", "Embedded & Edge AI"),
    ("mining automation", "Mining Automation"),
    ("mining", "Mining & Resources"),
    ("systems engineer", "Systems Engineering"),
    ("systems integration", "Systems Engineering"),
    ("mechatronic", "Mechatronics"),
    ("electrical engineer", "Electrical"),
    ("machine learning", "Software & AI"),
    ("ml engineer", "Software & AI"),
    ("software engineer", "Software & AI"),
    ("test and validation", "Test & Validation"),
    ("validation engineer", "Test & Validation"),
]


def categorize(title: str, description: str = "") -> str:
    text = (title + " " + description[:500]).lower()
    for keyword, category in CATEGORY_RULES:
        if keyword in text:
            return category
    return "Other"


# Default profiles seeded on first run (all disabled).
DEFAULT_PROFILES: list[dict] = [
    {
        "name": "Australia Graduate Programs",
        "countries": ["australia"],
        "sites": ["indeed", "linkedin", "google"],
        "roles": [],
        "match_any": ["graduate", "engineering graduate", "technology graduate", "automation", "robotics", "systems engineer", "digital"],
        "match_at_least_one": ["graduate", "entry level", "early career"],
        "exclude": ["senior", "principal", "manager", "director", "lead", "10+ years", "15+ years"],
        "job_levels": ["Graduate Program", "Graduate Engineer", "Entry Level"],
        "career_fields": ["Automation and Control", "Robotics and Autonomous Systems", "Systems Engineering and Integration"],
        "results_wanted": 50,
        "hours_old": 168,
        "is_remote": False,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Mining Automation and Technology",
        "countries": ["australia", "canada"],
        "sites": ["indeed", "linkedin"],
        "roles": [],
        "match_any": ["mining automation", "autonomous haul", "fleet management", "mining technology", "underground automation"],
        "match_at_least_one": [],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": [],
        "career_fields": ["Mining Automation and Technology", "Automation and Control"],
        "results_wanted": 30,
        "hours_old": 168,
        "is_remote": False,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Robotics and Autonomous Systems",
        "countries": ["australia", "usa", "uk", "canada"],
        "sites": ["indeed", "linkedin", "google"],
        "roles": ["Robotics Engineer", "Autonomous Systems Engineer", "Autonomy Engineer", "Robotics Software Engineer", "Mobile Robotics Engineer"],
        "match_any": ["robotics", "autonomous systems", "autonomy", "ros", "ros2"],
        "match_at_least_one": [],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": [],
        "career_fields": ["Robotics and Autonomous Systems"],
        "results_wanted": 50,
        "hours_old": 168,
        "is_remote": False,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Computer Vision, Lidar and Sensor Fusion",
        "countries": ["australia", "usa", "uk", "canada", "germany"],
        "sites": ["indeed", "linkedin", "google"],
        "roles": ["Perception Engineer", "Sensor Fusion Engineer", "Navigation Engineer"],
        "match_any": ["perception", "computer vision", "lidar", "sensor fusion", "slam", "point cloud", "object detection"],
        "match_at_least_one": [],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": [],
        "career_fields": ["Perception and Computer Vision", "Sensor Fusion and Lidar"],
        "results_wanted": 40,
        "hours_old": 168,
        "is_remote": True,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Systems Engineering and Integration",
        "countries": ["australia", "usa", "uk"],
        "sites": ["indeed", "linkedin"],
        "roles": ["Robotics Integration Engineer", "Systems Engineering and Integration"],
        "match_any": ["systems engineer", "systems integration", "test and validation", "verification and validation"],
        "match_at_least_one": [],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": [],
        "career_fields": ["Systems Engineering and Integration"],
        "results_wanted": 30,
        "hours_old": 168,
        "is_remote": False,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Embedded Systems and Edge AI",
        "countries": ["australia", "usa", "uk", "germany"],
        "sites": ["indeed", "linkedin", "google"],
        "roles": [],
        "match_any": ["embedded", "firmware", "edge ai", "fpga", "rtos", "embedded linux", "c++ embedded"],
        "match_at_least_one": [],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": [],
        "career_fields": ["Embedded Systems and Edge AI"],
        "results_wanted": 30,
        "hours_old": 168,
        "is_remote": False,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Software Engineering and Applied AI",
        "countries": ["australia", "usa", "uk", "canada"],
        "sites": ["indeed", "linkedin", "google"],
        "roles": [],
        "match_any": ["software engineer", "machine learning engineer", "applied ai", "c++ developer", "python developer"],
        "match_at_least_one": ["robotics", "autonomous", "automation", "AI", "ml"],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": [],
        "career_fields": ["Software Engineering and AI"],
        "results_wanted": 40,
        "hours_old": 168,
        "is_remote": True,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Canada Mining and Robotics Roles",
        "countries": ["canada"],
        "sites": ["indeed", "linkedin"],
        "roles": [],
        "match_any": ["robotics", "mining automation", "autonomous systems", "controls engineer"],
        "match_at_least_one": [],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": [],
        "career_fields": ["Robotics and Autonomous Systems", "Mining Automation and Technology"],
        "results_wanted": 30,
        "hours_old": 168,
        "is_remote": False,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "Nordic Industrial R&D Roles",
        "countries": ["sweden", "norway", "denmark", "finland"],
        "sites": ["indeed", "linkedin"],
        "roles": [],
        "match_any": ["robotics", "autonomous", "automation", "mechatronics", "embedded"],
        "match_at_least_one": [],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": [],
        "career_fields": ["Robotics and Autonomous Systems", "Automation and Control"],
        "results_wanted": 20,
        "hours_old": 168,
        "is_remote": False,
        "use_ats": False,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
    {
        "name": "UK Graduate Engineering Schemes",
        "countries": ["uk"],
        "sites": ["indeed", "linkedin"],
        "roles": [],
        "match_any": ["graduate scheme", "graduate programme", "graduate engineer", "graduate robotics", "graduate automation"],
        "match_at_least_one": ["graduate", "entry level", "early career"],
        "exclude": ["senior", "principal", "manager", "director", "10+ years"],
        "job_levels": ["Graduate Program", "Graduate Engineer", "Entry Level"],
        "career_fields": ["Robotics and Autonomous Systems", "Graduate and Entry Level"],
        "results_wanted": 30,
        "hours_old": 168,
        "is_remote": False,
        "use_ats": True,
        "schedule_frequency": "daily",
        "schedule_time": "07:00",
        "timezone": "Australia/Sydney",
    },
]
